# Generated by Django 4.2.3 on 2023-07-19 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_postusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostUsers',
        ),
    ]
